### ISSUE TITLE
Getting hung on certain searches

### ISSUE THREAD

**Issue by CrepuscularPulchritude** [ccf-2012/seedcross#21]
I rarely make it through a search of 20 items before SC appears to hang on one specific search. I can leave it for 10+ minutes and it will still be on that search. Sometimes it's single file torrents, sometimes it's torrents with many folders. Some contain video files, others contain games. They've all been torrents that have no foreign characters, just simple latin alphabet, numbers, and common symbols like . _ - etc.
If I were to clear the list of records then start over it hangs on the same searches
I'm not 100% sure how to grab logs, by my best guess this is an example of one that failed just a few searches in

`Starting at:02/15/2023, 20:24:04
Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 466, in iterTorrents
    matchingResults = searcher.search(searchData, log, guess_cat=cat)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 114, in search
    trim_result = self.loadToIndexResult(result_json)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 262, in loadToIndexResult
    categories=result['categories'],
KeyError: 'categories'
Marking task proceed_cross_seed as failed`

**Comment by AnyColorIWant** [comment]
Hanging for me as well. Here's an example-

Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/mnt/mpathg/anycoloriwant/virtualenv/lib/python3.11/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/mnt/mpathg/anycoloriwant/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/mnt/mpathg/anycoloriwant/seedcross/crseed/CrossSeedAutoDL.py", line 477, in iterTorrents
    matchingResults = searcher.search(searchData, log, guess_cat=cat)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/mpathg/anycoloriwant/seedcross/crseed/CrossSeedAutoDL.py", line 114, in search
    trim_result = self.loadToIndexResult(result_json)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/mpathg/anycoloriwant/seedcross/crseed/CrossSeedAutoDL.py", line 273, in loadToIndexResult
    TrackerType=result['TrackerType'],
                ~~~~~~^^^^^^^^^^^^^^^
KeyError: 'TrackerType'
Marking task proceed_cross_seed as failed
