### ISSUE TITLE
KeyError: 'downloadUrl'

### ISSUE THREAD

**Issue by Horridge** [ccf-2012/seedcross#29]
Error observed in log, and task proceed_cross_seed is marked as failed; seemingly at random. Will just hang when searching for some items.

`Traceback (most recent call last):`
  `File "/usr/local/lib/python3.11/site-packages/background_task/tasks.py", line 43, in bg_runner`
    `func(*args, **kwargs)`
  `File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask`
    `iterTorrents(dlclient, param, log)`
  `File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 466, in iterTorrents`
    `matchingResults = searcher.search(searchData, log, guess_cat=cat)`
                      `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
  `File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 114, in search`
    `trim_result = self.loadToIndexResult(result_json)`
                  `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
  `File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 264, in loadToIndexResult`
    `downloadUrl=result['downloadUrl'],`
                `~~~~~~^^^^^^^^^^^^^^^`
`KeyError: 'downloadUrl'`

**Comment by chust4** [comment]
I'm having same issue: 
`Rescheduling proceed_cross_seed

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/background_task/tasks.py", line 43, in bg_runner

    func(*args, **kwargs)

  File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask

    iterTorrents(dlclient, param, log)

  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 466, in iterTorrents

    matchingResults = searcher.search(searchData, log, guess_cat=cat)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 114, in search

    trim_result = self.loadToIndexResult(result_json)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 264, in loadToIndexResult

    downloadUrl=result['downloadUrl'],

                ~~~~~~^^^^^^^^^^^^^^^

KeyError: 'downloadUrl'

Marking task proceed_cross_seed as failed`

**Comment by ccf-2012** [comment]
don't know why some search return torrent without downloadUrl, any how i add a protection in the code.
commit in the github, not docker.

**Comment by erichlf** [comment]
This is still not in docker. Is there an eta on updating the docker image?

**Comment by mckellar11** [comment]
Still having this issue in 2025.. any fix?
