### ISSUE TITLE
Stops at "Loading torrents in the client" "KeyError: b'download_location'"

### ISSUE THREAD

**Issue by tordenflesk** [ccf-2012/seedcross#9]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/code/seedcross/crseed/tasks.py", line 80, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 425, in iterTorrents
    torList = dlclient.loadTorrents()
  File "/code/seedcross/crseed/torclient.py", line 384, in loadTorrents
    st = self.mkSeedTor(deTor)
  File "/code/seedcross/crseed/torclient.py", line 278, in mkSeedTor
    save_path=deTor[b'download_location'].decode("utf-8"),
KeyError: b'download_location'
Marking task proceed_cross_seed as failed
```

**Comment by ccf-2012** [comment]
The log you posted means you are cross-seeding torrent on a deluge client, and failed when loading torrents.
are you failed on the first torrent? 
what's the version of the deluge client?

**Comment by tordenflesk** [comment]
Deluge 1.3.15
This is the "log" in the SeedCross UI:
```
Starting at:03/28/2022, 13:48:00
Connecting: 10.0.0.28
Connecting to 10.0.0.28:58846
Loading torrents in the client
```

**Comment by ccf-2012** [comment]
would you please have a test like this:

1. in an environment with python 3
```sh 
pip3 install deluge-client
```

2.  edit a file, let's say `de.py`, modify the parameters in `DelugeRPCClient` to connect your deluge
```py
from deluge_client import DelugeRPCClient

client = DelugeRPCClient('deluge.host', 12345, 'username', 'password')
client.connect()
tor_list = client.call('core.get_torrents_status', {}, [])

#for deTor in tor_list.values():
#	print(deTor)
detor = tor_list.popitem()
print(detor)
```

3. run `python3 de.py`, and see what fields this client has.

**Comment by tordenflesk** [comment]
```
(b'2bf269349d70133020147fae551746f32d88b38e', {b'comment': b'SuperBits.Org', b'active_time': 1095640, b'i
s_seed': True, b'move_completed_path': b'/POOL00/downloads/complete/SONARR', b'private': True, b'total_pa
yload_upload': 0, b'seed_rank': 181, b'seeding_time': 1094636, b'prioritize_first_last': False, b'downloa
d_payload_rate': 0, b'message': b'OK', b'num_peers': 0, b'max_connections': -1, b'compact': False, b'eta'
: 0, b'ratio': 0.0, b'file_priorities': (4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4), b'max_upload_speed': -1,
 b'save_path': b'/POOL00/downloads/complete/SONARR', b'movetools_message': None, b'tracker_host': b'super
bits.org', b'total_uploaded': 0, b'files': ({b'index': 0, b'size': 300000000, b'offset': 0, b'path': b'FB
I.Most.Wanted.S03E14.1080p.WEB.h264-GOSSIP/fbi.most.wanted.s03e14.1080p.web.h264-gossip.r03'}, {b'index':
 1, b'size': 300000000, b'offset': 300000000, b'path': b'FBI.Most.Wanted.S03E14.1080p.WEB.h264-GOSSIP/fbi
.most.wanted.s03e14.1080p.web.h264-gossip.r05'}, {b'index': 2, b'size': 219906795, b'offset': 600000000,
b'path': b'FBI.Most.Wanted.S03E14.1080p.WEB.h264-GOSSIP/fbi.most.wanted.s03e14.1080p.web.h264-gossip.r08'
}, {b'index': 3, b'size': 300000000, b'offset': 819906795, b'path': b'FBI.Most.Wanted.S03E14.1080p.WEB.h2
64-GOSSIP/fbi.most.wanted.s03e14.1080p.web.h264-gossip.r04'}, {b'index': 4, b'size': 300000000, b'offset'
: 1119906795, b'path': b'FBI.Most.Wanted.S03E14.1080p.WEB.h264-GOSSIP/fbi.most.wanted.s03e14.1080p.web.h2
64-gossip.r07'}, {b'index': 5, b'size': 300000000, b'offset': 1419906795, b'path': b'FBI.Most.Wanted.S03E
14.1080p.WEB.h264-GOSSIP/fbi.most.wanted.s03e14.1080p.web.h264-gossip.rar'}, {b'index': 6, b'size': 30000
0000, b'offset': 1719906795, b'path': b'FBI.Most.Wanted.S03E14.1080p.WEB.h264-GOSSIP/fbi.most.wanted.s03e
14.1080p.web.h264-gossip.r00'}, {b'index': 7, b'size': 300000000, b'offset': 2019906795, b'path': b'FBI.M
ost.Wanted.S03E14.1080p.WEB.h264-GOSSIP/fbi.most.wanted.s03e14.1080p.web.h264-gossip.r02'}, {b'index': 8,
 b'size': 300000000, b'offset': 2319906795, b'path': b'FBI.Most.Wanted.S03E14.1080p.WEB.h264-GOSSIP/fbi.m
ost.wanted.s03e14.1080p.web.h264-gossip.r06'}, {b'index': 9, b'size': 590, b'offset': 2619906795, b'path'
: b'FBI.Most.Wanted.S03E14.1080p.WEB.h264-GOSSIP/fbi.most.wanted.s03e14.1080p.web.h264-gossip.sfv'}, {b'i
ndex': 10, b'size': 74349354, b'offset': 2619907385, b'path': b'FBI.Most.Wanted.S03E14.1080p.WEB.h264-GOS
SIP/Sample/fbi.most.wanted.s03e14.1080p.web.h264-gossip-sample.mkv'}, {b'index': 11, b'size': 952, b'offs
et': 2694256739, b'path': b'FBI.Most.Wanted.S03E14.1080p.WEB.h264-GOSSIP/fbi.most.wanted.s03e14.1080p.web
.h264-gossip.nfo'}, {b'index': 12, b'size': 300000000, b'offset': 2694257691, b'path': b'FBI.Most.Wanted.
S03E14.1080p.WEB.h264-GOSSIP/fbi.most.wanted.s03e14.1080p.web.h264-gossip.r01'}), b'num_pieces': 714, b't
otal_seeds': 11, b'peers': (), b'stop_at_ratio': False, b'move_on_completed_path': b'/POOL00/downloads/co
mplete/SONARR', b'num_seeds': 0, b'name': b'FBI.Most.Wanted.S03E14.1080p.WEB.h264-GOSSIP', b'trackers': (
{b'send_stats': True, b'fails': 0, b'verified': False, b'scrape_incomplete': -1, b'min_announce': None, b
'scrape_downloaded': -1, b'url': b'https://tracker.superbits.org/tracker.php/5e60dd2b4d36a8b3efd9bbd22c8e
2bbf/announce', b'last_error': {b'category': b'system', b'value': 0}, b'fail_limit': 0, b'next_announce':
 None, b'complete_sent': False, b'source': 2, b'trackerid': b'', b'start_sent': False, b'tier': 0, b'scra
pe_complete': -1, b'message': b'', b'updating': False}, {b'send_stats': True, b'fails': 0, b'verified': F
alse, b'scrape_incomplete': -1, b'min_announce': None, b'scrape_downloaded': -1, b'url': b'https://superb
its.org/tracker.php/5e60dd2b4d36a8b3efd9bbd22c8e2bbf/announce', b'last_error': {b'category': b'system', b
'value': 0}, b'fail_limit': 0, b'next_announce': None, b'complete_sent': False, b'source': 2, b'trackerid
': b'', b'start_sent': False, b'tier': 0, b'scrape_complete': -1, b'message': b'', b'updating': False}, {
b'send_stats': True, b'fails': 0, b'verified': False, b'scrape_incomplete': -1, b'min_announce': None, b'
scrape_downloaded': -1, b'url': b'https://sptracker.cc/tracker.php/5e60dd2b4d36a8b3efd9bbd22c8e2bbf/annou
nce', b'last_error': {b'category': b'system', b'value': 0}, b'fail_limit': 0, b'next_announce': None, b'c
omplete_sent': False, b'source': 2, b'trackerid': b'', b'start_sent': False, b'tier': 0, b'scrape_complet
e': -1, b'message': b'', b'updating': False}), b'is_auto_managed': True, b'stop_ratio': 2.0, b'is_finishe
d': True, b'max_download_speed': -1, b'upload_payload_rate': 0, b'remove_at_ratio': False, b'paused': Fal
se, b'all_time_download': 2998862071, b'max_upload_slots': -1, b'total_wanted': 2994257691, b'file_progre
ss': (1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0), b'total_peers': 1, b'total_size':
 2994257691, b'label': b'sonarr', b'state': b'Seeding', b'tracker': b'https://superbits.org/tracker.php/5
e60dd2b4d36a8b3efd9bbd22c8e2bbf/announce', b'progress': 100.0, b'time_added': 1647280128.0, b'Move Status
': None, b'total_done': 2994257691, b'hash': b'2bf269349d70133020147fae551746f32d88b38e', b'next_announce
': 0, b'move_completed': True, b'piece_length': 4194304, b'move_on_completed': True, b'seeds_peers_ratio'
: 11.0, b'tracker_status': b'superbits.org: Announce OK', b'queue': -1, b'num_files': 13, b'distributed_c
opies': 1.0, b'total_payload_download': 0})
```

**Comment by ccf-2012** [comment]
# a183abbe6a

for deluge client, I have changed  field `download_location` to `save_path`
https://hub.docker.com/r/ccf2012/seedcross  is also updated.

the reason is that some client has `download_location` field and some doesn't, but they always has `save_path` field. (seems)

**Comment by sotiris-bos** [comment]
I have a similar issue on transmission.

```
Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 427, in iterTorrents
    torList = dlclient.loadTorrents()
  File "/code/seedcross/crseed/torclient.py", line 96, in loadTorrents
    st = self.mkSeedTor(trTor)
  File "/code/seedcross/crseed/torclient.py", line 68, in mkSeedTor
    tracker=self.abbrevTracker(trTor.trackers[0]),
IndexError: list index out of range
Marking task proceed_cross_seed as failed
```
